### ISSUE TITLE
http endpoint /health doesn't work

### ISSUE THREAD

**Issue by faxm0dem** [mcorbin/mirabelle#13]
The [documentation](https://www.mirabelle.mcorbin.fr/api/) states that the http endpoints `/healthz` and `/health` are equivalent.
However, the latter returns an error:

```
☠ curl -D /dev/stdout http://127.0.0.1:5558/health
HTTP/1.1 404 Not Found
Date: Tue, 19 Oct 2021 07:51:51 GMT
Content-Type: application/json
Content-Length: 48
Server: Jetty(9.4.31.v20200723)

{"error":"uri /health not found for method get"}
```

**Comment by mcorbin** [comment]
Fixed in https://github.com/mcorbin/mirabelle/commit/d2b2519b5de718a32b23ecb39b920326f9bde35d
