### ISSUE TITLE
Is it possible to extend mirabelle with macros ?

### ISSUE THREAD

**Issue by faxm0dem** [mcorbin/mirabelle#32]
I'd like to add a custom action based on another one.
In riemann I'd have written it like this:
```
(defmacro over_10
  "Passes on events whose metric is over 10"
  [& children]
  `(over 10 ~@children))
```

**Comment by mcorbin** [comment]
I don't think macro will work.

What you can do is write a function calling the underlying function used by the over action:

```clojure
(defn over-10*
  [ctx params & children]
  (apply a/over* ctx 10 children))
```

As said in the other issue, passing a parameter is mandatory for now because of a bug.

**Comment by mcorbin** [comment]
Actually this should work::

``` clojure
(defn over-10*
  [ctx & children]
  (apply a/over* ctx 10 children))

```

Then you can call it with

```clojure
(a/custom :my-custom-action
                        nil
                       (info))
```

**Comment by faxm0dem** [comment]
Using `apply` it shall be thanks !
